### ISSUE TITLE
Add multires_image_file_path to collection and item documents for thumbnails?

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-models#304]
Is it feasible to add to each Solr collection document and item document a multires_image_file_path to use to generate thumbnails using the image server? The value of this field would be the first child component's multires_image_file_path. Currently, I can get this path by querying for the first component of each item or collection being displayed, but I think it might make sense for this value to be in the Solr document for items and collections.

**Comment by coblej** [comment]
@corylown Rather than actually make this an index field on the collection and item documents, I suggest we add a method to SolrDocument to look up the first child and return the appropriate value.  If you make it an actual index field on the collection and item documents, then you have to account for updating it (at least potentially), every time a component is changed.

**Comment by corylown** [comment]
@coblej For now, I will add something like this to SolrDocument in ddr-public. The downside to this approach is that in the index view it requires doing a lookup for the image path for each result, usually ten but up to 100. Maybe it's fast enough not to be a problem, though.

**Comment by coblej** [comment]
@corylown The concern about performance is a legitimate one and what I suggested may not prove to be performant.  As I noted, the downside of storing it as an actual index field is determining all the possible situations in which it may need to be re-evaluated and re-indexed; e.g., a component is deleted (matters if it happens to be the first child of the first item), components or items are re-ordered, a new version of a content file is uploaded, etc.  I'm going to re-open this issue because, however we end up handling it, it should eventually be done in ddr-models so its available to all applications.

**Comment by corylown** [comment]
The point of all this is make larger thumbnails available to the grid index view (and possibly other locations). An alternative approach would be to generate the larger thumbnails on ingest to avoid the problems with the other two approaches.

**Comment by dchandekstark** [comment]
@corylown Is this effectively resolved now?

**Comment by corylown** [comment]
@dchandekstark -- it's resolved in ddr-public.

**Comment by dchandekstark** [comment]
Based on @corylown's comment I am resolving here.
