### ISSUE TITLE
Upgrade hydra-derivatives

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#5]

**Comment by coblej** [comment]
@dchandekstark The ddr-models gem spec does not currently specify a version for hydra-derivatives.  I assume the intent of this issue is add a version specification for hydra-derivatives to the gem spec; presumably something like '~> 1.0' ?

**Comment by coblej** [comment]
@dchandekstark Actually, we can't use hydra-derivatives 1.0 since it depends on ActiveFedora 9.  I think the latest version we can use is 0.1.1, which appears to be latest stable pre-AF9 version.  Our servers are already using 0.1.1 so I don't think there is anything to do for this issue.  Or, am I missing something?

**Comment by coblej** [comment]
@dchandekstark Turns out it's a little more nuanced than I thought.  The latest released pre-AF9 version of hydra-derivatives is, as I noted, 0.1.1.  However, in github, there is a 0.1-stable branch that is actually ahead of 0.1.1.  And it looks like we may need the 0.1-stable code to do the JPEG2000 conversions.  At least, I get an error on my workstation when using 0.1.1 but not when using 0.1-stable.  Maybe I should see if anyone objects to releasing 0.1-stable as 0.1.2.

**Comment by dchandekstark** [comment]
I guess so, yeah.

**Comment by dchandekstark** [comment]
Sounds good. The other option is to roll our own. It's too bad that the tool is coupled with the repo object API.

**Comment by dchandekstark** [comment]
HD was removed in another issue.
